version: '3.1'
services:
  web:
    user: vscode
    working_dir: /workspace
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ../:/mnt
      - /mnt/.devcontainer
      - /mnt/extra-addons
      - ../test-project/:/workspace
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: sleep infinity
  db:
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data: